name: "ci"
run-name: "build & test"

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: "9.4"
          cabal-version: "3.8"
      - name: "Install dependencies"
        run: |
          sudo apt update
          sudo apt install gcc hlint ormolu make -y
      - name: "Format check"
        run: make format-check
      - name: "Lint"
        run: make lint
      - name: "Build"
        run: make build
      - name: "Test"
        run: make test
